### ISSUE TITLE
10.12.5 Graphics Memory only 31MB

### ISSUE THREAD

**Issue by PromiseYo** [corenel/XPS9550-macOS#11]
my laptop is i5 4k,use your clover config,  bios version 1.2.18 ,when i update to 1.2.25 ,i cant install.  1.2.18 install success,   but  Graphics Memory only 31MB,and brightness cant adjust. thanks

**Comment by corenel** [comment]
- BIOS 1.2.25 issue: https://github.com/wmchris/DellXPS15-9550-OSX/blob/master/Tutorial_10.12_Step7.md#osx-doesnt-boot-anymore-after-firmware-upgrade-to-1225-or-higher
 - 4K issue (since I don't have 4K display, I haven't tried it): https://github.com/wmchris/DellXPS15-9550-OSX/blob/0bb045ae8df72491d4dd0e4db5516afbd4a99c0d/10.12/Post-Install/AD-Kexts/UHD-Kexts/readme.md
 - Brightness adjustment works fine on my laptop.

**Comment by PromiseYo** [comment]
thanks！！
update firmware to 1.2.25 and boot successfully,but graphics memory still 31MB /(ㄒoㄒ)/~~.4k patch i also did. the same problem like before. Oh i change my original memory ram double 4g 2133 to double kingston HyperX 8g 2400. Any problem hd530 share momery if its frequency not right.Thanks sincerely~~~~
